# Generated by Django 4.1.1 on 2022-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_author_book_publisher_alter_genre_name_bookinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_code',
            field=models.CharField(help_text='13 symbols <a href="https://www.isbn-international.org/content/what-isbn">What is ISBN code?</a>', max_length=13, verbose_name='ISBN'),
        ),
    ]
