# Generated by Django 4.1.1 on 2022-09-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Borrowed'), ('g', 'Available')], default='g', help_text='Status', max_length=1),
        ),
    ]
