# Generated by Django 4.1.1 on 2022-09-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_bookinstance_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('r', 'Reserved'), ('b', 'Borrowed')], default='a', help_text='Status', max_length=1),
        ),
    ]
